### ISSUE TITLE
Not Generating Complete Epub Files for Articles on Nations

### ISSUE THREAD

**Issue by WolfgangDpunkt** [hauke96/wiki2book#49]
Firstly, I want to express my sincere gratitude and appreciation to the author of the wiki2book tool. It's an amazing piece of work and has been incredibly useful to me. 
However, I've come across an issue with generating incomplete Epub files for articles on nations in Wikipedia (Österreich, Deutschland, Japan ...). For instance, when I tried to generate an Epub file for the article on Belgium using the command `./wiki2book article Belgien -o Belgien.epub -d`, the resulting file only contained the headlines and was around 2.1mb in size, the same applies to any other nation article. 
[Belgien.epub.zip](https://github.com/hauke96/wiki2book/files/11413344/Belgien.epub.zip)

Nonetheless, I want to emphasize that I have only observed this behavior in articles of nations, and apparently only in currently existing ones. I have not encountered any issues with articles on historical nations such as Kaisertum Österreich. It seems that this particular template may be causing problems. I will provide a link to the debug log file, which shows that there were only two small errors related to the template evaluation API, but it's unclear if they are causing the issue. Once again, I would like to extend my gratitude to the author of this amazing tool.
I use the version currently available here.

 Here is the log file:

[belegien-log.txt](https://github.com/hauke96/wiki2book/files/11413354/belegien-log.txt)

**Comment by hauke96** [comment]
Hi, thanks for the bug report!

The problem is the evaluation of templates using the Wikipedia API with too long request URLs. I knew this problem will occur sooner or later with nested templates producing very very long URLs. Luckily the approach I used so far was not the smartest, so I was able to fix this problem.

In this particular case the nested `Positionskarte` templates, producing a map with the city names, were the problem. Unfortunately, the styling of the map is not only weird but also broken (s. screenshots) and will very likely not work on eBook readers anyway (but I haven't tried it). I therefore added the `Positionskarte` templates to the list of ignored templates, which means the map will not appear in the eBook.

![image](https://user-images.githubusercontent.com/9700906/236701988-46167686-aff6-4ee4-8c9f-c1f33a5cdf8a.png)
![image](https://user-images.githubusercontent.com/9700906/236701996-76865a8b-cfac-4805-aa1b-84eb08789112.png)

You can give it a try but not all problems are solved yet (e.g. the "Österreich#Geographie" section still contains the map in the eBook) but I'm working on it.

**Comment by WolfgangDpunkt** [comment]
Thank you for your quick and helpful response!
Ignoring the "position map" helped, now it produces Belgium correctly as an approx. 8mb epub that works perfectly.
