### ISSUE TITLE
Run wiki2book CLI in a Docker container

### ISSUE THREAD

**Issue by paddel10** [hauke96/wiki2book#70]
Hi, thank you for the tool!

### What would change in wiki2book?
I've written a Dockerfile which installs and runs wiki2book CLI in a container.

### What's the motivation behind this change?
Building and running wiki2book CLI in a dedicated environment. Users do not need to pay attention to installing dependencies. It would also extend the userbase to other systems ;-) (Windows, MacOS)

### What existing parts of wiki2book might be influenced by this change?
There are no changes to wiki2book CLI

### What alternatives are there?
Run a VM and manually install wiki2book CLI

### Additional context
Example how to run wiki2book CLI in a docker container
```
$ docker run -v "/home/pr/Documents/wiki2book/data:/home/builder" wiki2book:latest project /home/builder/unimog.json
```
Open issues: I wasn't able to install the fonts ttf-dejavu-ib and ttf-dejavu-emojiless (fontforge: symbol lookup error: /usr/lib/libpango-1.0.so.0: undefined symbol: g_once_init_leave_pointer)

I'd be happy if you would consider adding the Dockerfile to your project. If not that's okay

```
FROM archlinux:latest

# Update the repositories
RUN pacman -Syy

# Install packages needed
RUN pacman -S --noconfirm git base-devel sudo

# Set up a non-root user (used for installing packages)
RUN useradd -m builder
# Set the password for the user (change password as needed)
RUN echo 'builder:password' | chpasswd

# Add the user to the wheel (aka sudo) group
RUN usermod -aG wheel builder

# Allow passwordless sudo (optional)
RUN echo 'builder ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# Switch to the user and clone project
USER builder
WORKDIR /home/builder
RUN git clone https://aur.archlinux.org/wiki2book.git
WORKDIR /home/builder/wiki2book
RUN makepkg -si --noconfirm

# fonts - unable to install
# fontforge: symbol lookup error: /usr/lib/libpango-1.0.so.0: undefined symbol: g_once_init_leave_pointer
# WORKDIR /home/builder
# RUN git clone https://aur.archlinux.org/ttf-dejavu-ib.git
# WORKDIR /home/builder/ttf-dejavu-ib
# RUN makepkg -si --noconfirm

# WORKDIR /home/builder
# RUN git clone https://aur.archlinux.org/ttf-dejavu-emojiless.git
# WORKDIR /home/builder/ttf-dejavu-emojiless
# RUN makepkg -si --noconfirm

# Clean up
USER root
WORKDIR /home/builder
RUN rm -rf /home/builder/wiki2book
# RUN rm -rf /home/builder/ttf-dejavu-ib
# RUN rm -rf /home/builder/ttf-dejavu-emojiless

ENTRYPOINT ["wiki2book"]
```

**Comment by hauke96** [comment]
Thanks for the feature suggestion, the most important part is probably the last paragraph in this comment :D

First of all, these are my immediate thoughts on this:

* wiki2book is already available for Windows and MacOS (s. release page), no need to manually build this or use a docker-container with the linux version inside to just use it on non-Linux platforms.
* Fonts are completely optional and configurable. Using a container kind of limits the user to the fonts within the container. However, yes, it's possible to mount a volume containing other TTF files, even though it's of course inconvenient.
* But yes, pandoc and ImageMagick are currently (v0.1.1) needed.
* I'm trying to get rid of pandoc and ImageMagick or at least make them optional. In the future it'll be possible to use golang libraries for their functionalities (maybe this will be the default, who knows). The current `dev` branch contains changes for this, i.e. a configurable "OutputDriver" (s. [here](https://github.com/hauke96/wiki2book/blob/68f28b94bb859b0d50f42e72ded135d510c396cb/doc/configuration.md)).
* IMHOs:
  * Using docker as replacement for a package/dependency manager is bad practice and at least a huge overhead regarding tooling and performance.
  * I don't think more people will use wiki2book with this, because they must have a running docker environment on their system, which is not that common for non-IT people ;)
  * A docker-setup doesn't have any use for me personally and for me it's just something that needs to be maintained.

Will say: It's currently not really and in the long term even less necessary to have a docker container for wiki2book.

But I know some people (mis)using docker as a package-/dependency manager to execute scripts or commands. Therefore, I do see the use-case and here are some technical things that came to my mind:

* Your file doesn't contain the dependencies pandoc and ImageMagick, which would currently be the main selling point ;)
* I think a simple ubuntu base-image would be easier as it would make the Dockerfile shorter: Install pandoc, ImageMagick and some fonts using apt and download the wiki2book executable from GitHub. I think only six lines would be enough ;)

**My plan for this:**
Due to the above reasons, I currently won't add a docker setup to this repo (s. also [here](https://github.com/hauke96/wiki2book/tree/68f28b94bb859b0d50f42e72ded135d510c396cb?tab=readme-ov-file#issues-bugs-ideas)). If you're willing to create a fully functioning Dockerfile, maintaining it and maybe even publish it as image on dockerhub, than feel free to do so. If it's a proper and well maintained project, I'm happy to mention it in the wiki2book README/documentation.

**Comment by paddel10** [comment]
Many thanks for your feedback! I'm aware that running wiki2book in a container is an overhead but I consider it more of a teaser than a workhorse setup. People might run wiki2book without worrying about the depencencies.

Maintaining and even publishing it as an image on dockerhub is a good idea and I might consider it in the future.

Cheers

btw: I tried an ubuntu base-image first but was not able to install it (it might have been a dependency issue) and since ArchLinux already handles the dependencies I went that route.
